version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: cicrleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          keys: 'npm-packages'
          paths:
            - /src/node_packeages
      - run: npm run lint
  test:
    docker:
      - image: cicrleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: cicrleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm audit

workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
