version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
    
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm audit

workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
